#!/usr/bin/env bash
# Generated by ai-automations — shared constants for the ClickUp project agent.
# Override any value via the environment. CLICKUP_TOKEN comes from CI secrets.

export CLICKUP_TEAM_ID="${CLICKUP_TEAM_ID:-1300430000010578}"
export CLICKUP_LIST_ID="${CLICKUP_LIST_ID:-1300430000066500}"
# Status NAMES (ClickUp statuses are usually lowercase; matching is case-insensitive).
export STATUS_ANALYZE="${STATUS_ANALYZE:-To Do}"
export STATUS_IMPLEMENT="${STATUS_IMPLEMENT:-IN PROGRESS}"
# Enabled handlers (comma-separated). Fully implemented: tasks.
# lists/folders/goals/time are routed by the relay but skipped by the resolver
# until their playbooks land — enabling them is harmless, just inert.
export ENABLED_HANDLERS="${ENABLED_HANDLERS:-tasks}"
export AGENT_MARKER="${AGENT_MARKER:-🤖 Clickup Agent}"
export AI_BRAIN="${AI_BRAIN:-claude-code}"
export AI_MODEL="${AI_MODEL:-claude-sonnet-5}"
export STATE_BRANCH="${STATE_BRANCH:-clickup-agent-state}"
export STATE_DIR="${STATE_DIR:-.agent-state}"
export OUT_DIR="${OUT_DIR:-.agent-out}"
